"""Optional semantic understanding after structural CanonicalDocument assembly."""

from .annotator import (
    SEMANTIC_ANNOTATOR_VERSION,
    SemanticAnnotationError,
    SemanticAnnotationPolicy,
    SemanticAnnotationResult,
    SemanticAnnotator,
)
from .heuristic import (
    HEURISTIC_SEMANTIC_POLICY_VERSION,
    HEURISTIC_SEMANTIC_PROVIDER_VERSION,
    HeuristicSemanticPolicy,
    HeuristicSemanticProvider,
    LanguageRoutingMode,
    SemanticMarkerRule,
)
from .fingerprint import (
    SEMANTIC_CONFIGURATION_FINGERPRINT_VERSION,
    semantic_configuration_hash,
    semantic_provider_capabilities_hash,
)
from .model import (
    MODEL_SEMANTIC_PROVIDER_POLICY_VERSION,
    MODEL_SEMANTIC_PROVIDER_VERSION,
    ModelSemanticProvider,
    ModelSemanticProviderError,
    ModelSemanticProviderPolicy,
    SemanticModelBackend,
    SemanticModelBatch,
)
from .provider import (
    EXTRACTIVE_SEMANTIC_ANNOTATION_TYPES,
    SEMANTIC_PROVIDER_PROTOCOL_VERSION,
    SemanticCandidate,
    SemanticCapability,
    SemanticOntologyLabel,
    SemanticProvider,
    SemanticProviderCapabilities,
    SemanticRequest,
    SemanticRequestSegment,
    SemanticTargetKind,
)
from .request import (
    SEMANTIC_REQUEST_BUILDER_VERSION,
    SemanticContextPlanner,
    SemanticRequestBuilder,
)
from .quality import SemanticCoverageReport, evaluate_semantic_coverage
from .providers.role_classifier import (
    ROLE_CLASSIFIER_ANNOTATION_TYPES,
    ROLE_CLASSIFIER_CAPABILITY_NAME,
    ROLE_CLASSIFIER_POLICY_VERSION,
    ROLE_CLASSIFIER_PROVIDER_VERSION,
    RoleClassifierBackend,
    RoleClassifierBatch,
    RoleClassifierCalibrator,
    RoleClassifierLogit,
    RoleClassifierPrediction,
    RoleClassifierProbability,
    RoleClassifierProvider,
    RoleClassifierProviderError,
    RoleClassifierProviderPolicy,
    RoleClassifierThreshold,
)

__all__ = [
    "HEURISTIC_SEMANTIC_PROVIDER_VERSION",
    "HEURISTIC_SEMANTIC_POLICY_VERSION",
    "SEMANTIC_ANNOTATOR_VERSION",
    "SEMANTIC_PROVIDER_PROTOCOL_VERSION",
    "SEMANTIC_REQUEST_BUILDER_VERSION",
    "EXTRACTIVE_SEMANTIC_ANNOTATION_TYPES",
    "HeuristicSemanticProvider",
    "HeuristicSemanticPolicy",
    "LanguageRoutingMode",
    "MODEL_SEMANTIC_PROVIDER_POLICY_VERSION",
    "MODEL_SEMANTIC_PROVIDER_VERSION",
    "ROLE_CLASSIFIER_ANNOTATION_TYPES",
    "ROLE_CLASSIFIER_CAPABILITY_NAME",
    "ROLE_CLASSIFIER_POLICY_VERSION",
    "ROLE_CLASSIFIER_PROVIDER_VERSION",
    "ModelSemanticProvider",
    "ModelSemanticProviderError",
    "ModelSemanticProviderPolicy",
    "RoleClassifierBackend",
    "RoleClassifierBatch",
    "RoleClassifierCalibrator",
    "RoleClassifierLogit",
    "RoleClassifierPrediction",
    "RoleClassifierProbability",
    "RoleClassifierProvider",
    "RoleClassifierProviderError",
    "RoleClassifierProviderPolicy",
    "RoleClassifierThreshold",
    "SemanticAnnotationError",
    "SemanticAnnotationPolicy",
    "SemanticAnnotationResult",
    "SemanticAnnotator",
    "SemanticCandidate",
    "SemanticCapability",
    "SemanticCoverageReport",
    "SemanticContextPlanner",
    "SemanticOntologyLabel",
    "SemanticProvider",
    "SemanticProviderCapabilities",
    "SemanticRequest",
    "SemanticRequestBuilder",
    "SemanticRequestSegment",
    "SemanticMarkerRule",
    "SemanticModelBackend",
    "SemanticModelBatch",
    "SemanticTargetKind",
    "evaluate_semantic_coverage",
    "semantic_configuration_hash",
    "semantic_provider_capabilities_hash",
    "SEMANTIC_CONFIGURATION_FINGERPRINT_VERSION",
]
